Repository jenkinsci/git-parameter-plugin, pull requests merged in 2023-07, with the labels that each got.

#99 Refresh plugin for June 2023
  .mvn/extensions.xml
  .mvn/maven.config
  pom.xml
Labels: internal

#97 Add UI Acceptance test
  pom.xml
  src/test/java/net/uaznia/lukanus/hudson/plugins/gitparameter/UiAcceptanceTest.java
  src/test/resources/net/uaznia/lukanus/hudson/plugins/gitparameter/UiAcceptanceTest/test/jobs/test/config.xml
Labels: test

#100 [JENKINS-71567] Fix param name including & are not recognized
  src/main/resources/net/uaznia/lukanus/hudson/plugins/gitparameter/GitParameterDefinition/index.jelly
Labels: bug

#98 refactor: Do not rely on prototype.js
  src/main/resources/net/uaznia/lukanus/hudson/plugins/gitparameter/javascript/git-parameter-select.js
  src/main/resources/net/uaznia/lukanus/hudson/plugins/gitparameter/javascript/git-parameter.js
Labels: internal

#101 Add Jenkins Security Scan
  .github/workflows/jenkins-security-scan.yml
Labels: internal

#105 Format project with Spotless
  pom.xml
  src/main/java/net/uaznia/lukanus/hudson/plugins/gitparameter/Consts.java
  src/main/java/net/uaznia/lukanus/hudson/plugins/gitparameter/FilePathWrapper.java
  src/main/java/net/uaznia/lukanus/hudson/plugins/gitparameter/GitParameterDefinition.java
  src/main/java/net/uaznia/lukanus/hudson/plugins/gitparameter/GitParameterRebuild.java
  src/main/java/net/uaznia/lukanus/hudson/plugins/gitparameter/GitParameterValue.java
  src/main/java/net/uaznia/lukanus/hudson/plugins/gitparameter/RevisionInfoFactory.java
  src/main/java/net/uaznia/lukanus/hudson/plugins/gitparameter/SelectedValue.java
  src/main/java/net/uaznia/lukanus/hudson/plugins/gitparameter/SmartNumberStringComparer.java
  src/main/java/net/uaznia/lukanus/hudson/plugins/gitparameter/SortMode.java
  src/main/java/net/uaznia/lukanus/hudson/plugins/gitparameter/Utils.java
  src/main/java/net/uaznia/lukanus/hudson/plugins/gitparameter/jobs/AbstractJobWrapper.java
  src/main/java/net/uaznia/lukanus/hudson/plugins/gitparameter/jobs/AbstractProjectJobWrapper.java
  src/main/java/net/uaznia/lukanus/hudson/plugins/gitparameter/jobs/JobWrapper.java
  src/main/java/net/uaznia/lukanus/hudson/plugins/gitparameter/jobs/JobWrapperFactory.java
  src/main/java/net/uaznia/lukanus/hudson/plugins/gitparameter/jobs/WorkflowJobWrapper.java
  src/main/java/net/uaznia/lukanus/hudson/plugins/gitparameter/model/ItemsErrorModel.java
  src/main/java/net/uaznia/lukanus/hudson/plugins/gitparameter/scms/EmptySCM.java
  src/main/java/net/uaznia/lukanus/hudson/plugins/gitparameter/scms/MultiSCM.java
  src/main/java/net/uaznia/lukanus/hudson/plugins/gitparameter/scms/ProxySCM.java
  src/main/java/net/uaznia/lukanus/hudson/plugins/gitparameter/scms/RepoSCM.java
  src/main/java/net/uaznia/lukanus/hudson/plugins/gitparameter/scms/SCMFactory.java
  src/main/java/net/uaznia/lukanus/hudson/plugins/gitparameter/scms/SCMWrapper.java
  src/main/java/net/uaznia/lukanus/hudson/plugins/gitparameter/scms/SingleSCM.java
  src/test/java/net/uaznia/lukanus/hudson/plugins/gitparameter/BasicTests.java
  src/test/java/net/uaznia/lukanus/hudson/plugins/gitparameter/GitParameterDefinitionTest.java
  src/test/java/net/uaznia/lukanus/hudson/plugins/gitparameter/RevisionInfoFactoryTest.java
  src/test/java/net/uaznia/lukanus/hudson/plugins/gitparameter/SmartNumberStringComparerTest.java
  src/test/java/net/uaznia/lukanus/hudson/plugins/gitparameter/SortTest.java
  src/test/java/net/uaznia/lukanus/hudson/plugins/gitparameter/UiAcceptanceTest.java
Labels: skip-changelog
